In [ ]:
#6
import numpy as np
import random
from scipy.spatial.distance import cdist
from scipy.cluster.vq import vq, whiten
def kmean (a, book, tresh = 1e-05):
    tmp=1.
    d=0.
    n=int(a.size/a[0].size)
    codebook = np.array(book)
    k = int(book.size/2)
        
    while abs(tmp-d) > tresh:
        d=tmp
        s = np.argmin(cdist(a,codebook), axis=1)
        for i in range(k):
            l=[]
            for j in range(n):
                if np.any(s[j]==i):
                    l.append(a[j])
            codebook[i]=np.mean(l,0)
        tmp=np.std(codebook)
    return(codebook,d)



In [ ]:
features  = np.array([[ 1.9,2.3],
                    [ 1.5,2.5],
                    [ 0.8,0.6],
                    [ 0.4,1.8],
                    [ 0.1,0.1],
                    [ 0.2,1.8],
                    [ 2.0,0.5],
                    [ 0.3,1.5],
                    [ 1.0,1.0]])
whitened = whiten(features)
book = np.array((whitened[0],whitened[2]))
kmean(whitened,book)


In [14]:
#1
import numpy as np
a=np.random.random((10,3))
print(a,"\n")
z=np.min(abs(a-0.5),1)
x=z+0.5
y=0.5-z
min=(a[:,0]==x)+(a[:,1]==x)+(a[:,2]==x)
y[min]=x[min]
print(y)


[[0.71849214 0.94025115 0.06237014]
 [0.6073561  0.27816128 0.26988173]
 [0.2109263  0.75373948 0.78666226]
 [0.29941371 0.50528554 0.9299385 ]
 [0.77726313 0.85640386 0.96707018]
 [0.67086774 0.81529453 0.20830047]
 [0.88002336 0.81758391 0.07964624]
 [0.21898743 0.8484765  0.97533203]
 [0.67921894 0.31645813 0.56890642]
 [0.88732157 0.51686236 0.62639193]] 

[0.71849214 0.6073561  0.75373948 0.50528554 0.77726313 0.67086774
 0.81758391 0.21898743 0.56890642 0.51686236]


In [15]:
#2
import numpy as np
a=np.random.random((6,6))
print (a ,"\n")
print((np.sum(a,axis=1))/(np.min(a,axis=0)))

[[0.59036444 0.8492458  0.05275047 0.32803133 0.79698078 0.90079143]
 [0.75268956 0.06452151 0.9119762  0.03516616 0.51255703 0.45181548]
 [0.73830952 0.68526895 0.88026959 0.01303389 0.65234517 0.85293325]
 [0.75619061 0.44101551 0.67513318 0.90976472 0.06587565 0.50627813]
 [0.2617418  0.69591209 0.50083815 0.57740606 0.45388305 0.21538011]
 [0.666436   0.96509975 0.15305203 0.1585733  0.77176606 0.88043396]] 

[ 13.4413543   42.29172564  72.45736604 257.34904122  41.06466178
  16.69309725]


In [24]:
#3
import numpy as np
x=np.array([6,2,0,3,0,0,5,7,0])
tmp =x==0
tmp[x.size-1]=False
tmp=~np.roll(tmp,1)
x[tmp]=0
print(str(np.max(x)))

5


In [23]:
#5
import numpy as np
n=4
a=np.arange(n*n).reshape(n,n)
b=np.array(a).reshape(n*n)

x={ }
y={ }
x.update({0: [0]})
vector=b[n-1::n-1]
y.update({n-1:list(vector[:-1])})
for i in range(1,n-1):
    x.update({i: list(b[i::n-1][:i+1])})
    y.update({i+n-1:list(b[i::n-1][i+1:])})

y.update({2*n-2: [n*n-1]})
x.update(y)
print(x)

{0: [0], 1: [1, 4], 2: [2, 5, 8], 3: [3, 6, 9, 12], 4: [7, 10, 13], 5: [11, 14], 6: [15]}


In [27]:
#4
import numpy as np
x=np.ones(10)
i=np.array([0,1,2,3,5,5,5,8])
size=x.size
x +=np.bincount(i, minlength=size)
print(x)

[2. 2. 2. 2. 1. 4. 1. 1. 2. 1.]
