In [ ]:
#6
import numpy as np
import random
from scipy.spatial.distance import cdist
from scipy.cluster.vq import vq, whiten
def kmean (a, book, tresh = 1e-05):
    tmp=1.
    d=0.
    n=int(a.size/a[0].size)
    codebook = np.array(book)
    k = int(book.size/2)
        
    while abs(tmp-d) > tresh:
        d=tmp
        s = np.argmin(cdist(a,codebook), axis=1)
        for i in range(k):
            l=[]
            for j in range(n):
                if np.any(s[j]==i):
                    l.append(a[j])
            codebook[i]=np.mean(l,0)
        tmp=np.std(codebook)
    return(codebook,d)



In [ ]:
features  = np.array([[ 1.9,2.3],
                    [ 1.5,2.5],
                    [ 0.8,0.6],
                    [ 0.4,1.8],
                    [ 0.1,0.1],
                    [ 0.2,1.8],
                    [ 2.0,0.5],
                    [ 0.3,1.5],
                    [ 1.0,1.0]])
whitened = whiten(features)
book = np.array((whitened[0],whitened[2]))
kmean(whitened,book)


In [19]:
#1
import numpy as np
a=np.random.random((10,3))
print(a,"\n")
np.abs(a-0.5).argmin()



[[0.35567506 0.04554155 0.78470264]
 [0.66872848 0.6462302  0.32027302]
 [0.04008228 0.63759404 0.69022343]
 [0.54204933 0.39781564 0.69739156]
 [0.53701322 0.84705779 0.19071276]
 [0.19528068 0.89336539 0.08419755]
 [0.62886351 0.19182125 0.5432124 ]
 [0.27341481 0.45750626 0.02107052]
 [0.32888278 0.95949157 0.45910842]
 [0.04305704 0.880606   0.59098838]] 

12


In [15]:
#2
import numpy as np
a=np.random.random((6,6))
print (a ,"\n")
print((np.sum(a,axis=1))/(np.min(a,axis=0)))

[[0.59036444 0.8492458  0.05275047 0.32803133 0.79698078 0.90079143]
 [0.75268956 0.06452151 0.9119762  0.03516616 0.51255703 0.45181548]
 [0.73830952 0.68526895 0.88026959 0.01303389 0.65234517 0.85293325]
 [0.75619061 0.44101551 0.67513318 0.90976472 0.06587565 0.50627813]
 [0.2617418  0.69591209 0.50083815 0.57740606 0.45388305 0.21538011]
 [0.666436   0.96509975 0.15305203 0.1585733  0.77176606 0.88043396]] 

[ 13.4413543   42.29172564  72.45736604 257.34904122  41.06466178
  16.69309725]


In [13]:
#3
import numpy as np
x=np.array([6,2,0,3,0,0,5,7,0])
tmp =x==0
print (x[1:][tmp[:-1]].max())

5


In [55]:
#5
import numpy as np
n=4
a=np.arange(n*n).reshape(n,n)
b=np.array(a).reshape(n*n)
d = { }
for i in range (2*n-1):
    d.update ({i:list((b[i::n-1][:i+1]))}) #фактически сам код занимает две строчки
print (d)

{0: [0], 1: [1, 4], 2: [2, 5, 8], 3: [3, 6, 9, 12], 4: [4, 7, 10, 13], 5: [5, 8, 11, 14], 6: [6, 9, 12, 15]}


In [2]:
#4
import numpy as np
x=np.ones(10)
i=np.array([0,1,2,3,5,5,5,8])
size=x.size
print (x+np.bincount(i, minlength=size))


[2. 2. 2. 2. 1. 4. 1. 1. 2. 1.]
